include:
  - ./docker-compose-base.yml

services:
  ragflow:
    #    depends_on:
    #      mysql:
    #        condition: service_healthy
    image: ${RAGFLOW_IMAGE}
    container_name: ragflow-server
    ports:
      # Map từ cổng trong container (9380) ra cổng host = 25019
      - "${SVR_HTTP_PORT}:9380"
      # Thay vì 80:80 và 443:443, ta chỉ dùng 80 -> 25020
      # 443 có thể bỏ hoặc map ra cổng khác nếu muốn
      - "25020:80"
      # Có thể bỏ dòng dưới nếu không dùng HTTPS
      # - "25021:443"
    volumes:
      - ./ragflow-logs:/ragflow/logs
      - ./nginx/ragflow.conf:/etc/nginx/conf.d/ragflow.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    env_file: .env
    environment:
      - TZ=${TIMEZONE}
      - HF_ENDPOINT=${HF_ENDPOINT}
      - MACOS=${MACOS}
    networks:
      - ragflow
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
